server:
  port: 3000
spring:
  application:
    name: studyhub-crowd-redis
  redis:
    host: 192.168.0.105
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

logging:
  level:
    com.studyhub.crowd.test: debug