server:
  port: 4000
spring:
  application:
    name: studyhub-crowd-auth

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.0.105
  session:
    store-type: redis
send:
  email:
    sendEmailAccount: "3162728464@qq.com"
    sendEmailPassword: ""
    sendEmailSMTPServer: "smtp.qq.com"
    smtpPort: "465"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/


