server:
  port: 80
spring:
  application:
    name: studyhub-crowd-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
zuul:
  ignored-services: "*"
  routes:
    crowd-protal:
      service-id: studyhub-crowd-auth
      path: /**
ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间

